# Assignment 1: NumPy and Pandas Fundamentals - Solution

**Name:** Hamzat Tiamiyu Ustaz

In [1]:
import numpy as np
import pandas as pd


---
## Part A: NumPy Array Operations (30 points)

### Question 1: Revenue Simulation (10 points)

You run a small Nigerian market stall selling 4 products. Simulate 30 days of business:

**Requirements:**
1. Generate daily sales quantities for 4 products (use normal distribution)
   - Product A: mean=50, std=10
   - Product B: mean=30, std=5
   - Product C: mean=70, std=15
   - Product D: mean=40, std=8
2. Set random seed to your favorite number
3. Ensure no negative quantities (clip at 0)
4. Print the shape and first 5 days

**Deliverable:** Create a 30×4 NumPy array called `daily_sales`

In [2]:
# Set random seed for reproducibility
np.random.seed(42)

# Define parameters for 4 products
products = ['Product A', 'Product B', 'Product C', 'Product D']
means = [50, 30, 70, 40]
stds = [10, 5, 15, 8]

# Generate daily sales quantities for 30 days (30 x 4 array)
daily_sales = np.random.normal(loc=means, scale=stds, size=(30, 4))

# Clip negative values to 0 (no negative sales)
daily_sales = np.clip(daily_sales, 0, None)

# Display results
print("Shape of daily_sales array:", daily_sales.shape)
print("\nFirst 5 days of sales:")
print(daily_sales[:5].astype(int))
print("\nProducts:", products)

Shape of daily_sales array: (30, 4)

First 5 days of sales:
[[54 29 79 52]
 [47 28 93 46]
 [45 32 63 36]
 [52 20 44 35]
 [39 31 56 28]]

Products: ['Product A', 'Product B', 'Product C', 'Product D']


### Question 2: Financial Analysis (10 points)

Using the `daily_sales` array from Q1:

**Calculate:**
1. Total sales for each product over 30 days
2. Average daily sales per product
3. The day with maximum total sales (across all products)
4. How many days had total sales above the 30-day average?
5. Standard deviation of sales for each product

**Deliverable:** Print all results with clear labels

In [3]:
# 1. Total sales for each product over 30 days
total_sales_per_product = daily_sales.sum(axis=0)
print("1. Total sales for each product over 30 days:")
for i, product in enumerate(products):
    print(f"   {product}: {total_sales_per_product[i]:.2f} units")

# 2. Average daily sales per product
avg_daily_sales = daily_sales.mean(axis=0)
print("\n2. Average daily sales per product:")
for i, product in enumerate(products):
    print(f"   {product}: {avg_daily_sales[i]:.2f} units/day")

# 3. The day with maximum total sales (across all products)
daily_totals = daily_sales.sum(axis=1)
max_sales_day = np.argmax(daily_totals)
print(f"\n3. Day with maximum total sales: Day {max_sales_day + 1}")
print(f"   Total sales on that day: {daily_totals[max_sales_day]:.2f} units")

# 4. How many days had total sales above the 30-day average?
average_daily_total = daily_totals.mean()
days_above_average = np.sum(daily_totals > average_daily_total)
print(f"\n4. Days with total sales above 30-day average ({average_daily_total:.2f}): {days_above_average} days")

# 5. Standard deviation of sales for each product
sales_std = daily_sales.std(axis=0)
print("\n5. Standard deviation of sales for each product:")
for i, product in enumerate(products):
    print(f"   {product}: {sales_std[i]:.2f}")

1. Total sales for each product over 30 days:
   Product A: 1451.14 units
   Product B: 882.17 units
   Product C: 2060.75 units
   Product D: 1212.54 units

2. Average daily sales per product:
   Product A: 48.37 units/day
   Product B: 29.41 units/day
   Product C: 68.69 units/day
   Product D: 40.42 units/day

3. Day with maximum total sales: Day 27
   Total sales on that day: 220.10 units

4. Days with total sales above 30-day average (186.89): 17 days

5. Standard deviation of sales for each product:
   Product A: 6.42
   Product B: 4.69
   Product C: 15.60
   Product D: 7.99


### Question 3: Price & Revenue Calculation (10 points)

Your products have these prices: [200, 350, 150, 280] NGN

**Tasks:**
1. Calculate daily revenue (price × quantity for each product)
2. Calculate total revenue over 30 days
3. Apply a promotional discount:
   - Days 1-5: 15% off all products
   - Days 15-20: 10% off Product A and B only
   - Other days: no discount
4. Calculate total revenue with discounts
5. How much discount did you give away?

**Hint:** Use boolean indexing and broadcasting

In [4]:
# Product prices in NGN
prices = np.array([200, 350, 150, 280])

# 1. Calculate daily revenue (price × quantity for each product)
daily_revenue = daily_sales * prices
print("1. Daily Revenue (first 5 days):")
print(daily_revenue[:5].astype(int))

# 2. Calculate total revenue over 30 days
total_revenue = daily_revenue.sum()
print(f"\n2. Total revenue over 30 days: ₦{total_revenue:,.2f}")

# 3. Apply promotional discounts
# Create a copy for discounted revenue
discounted_revenue = daily_revenue.copy()

# Days 1-5: 15% off all products (indices 0-4)
discounted_revenue[0:5, :] *= 0.85

# Days 15-20: 10% off Product A and B only (indices 14-19, columns 0-1)
discounted_revenue[14:20, 0:2] *= 0.90

# 4. Calculate total revenue with discounts
total_discounted_revenue = discounted_revenue.sum()
print(f"\n3 & 4. Total revenue with discounts: ₦{total_discounted_revenue:,.2f}")

# 5. How much discount was given away?
total_discount = total_revenue - total_discounted_revenue
print(f"\n5. Total discount given away: ₦{total_discount:,.2f}")

# Breakdown of discount by promotion
discount_days_1_5 = daily_revenue[0:5, :].sum() * 0.15
discount_days_15_20 = daily_revenue[14:20, 0:2].sum() * 0.10
print(f"   - Days 1-5 (15% off all): ₦{discount_days_1_5:,.2f}")
print(f"   - Days 15-20 (10% off A&B): ₦{discount_days_15_20:,.2f}")

1. Daily Revenue (first 5 days):
[[10993 10258 11957 14611]
 [ 9531 10090 14053 12919]
 [ 9061 11449  9457 10156]
 [10483  7151  6618  9940]
 [ 7974 11049  8456  8036]]

2. Total revenue over 30 days: ₦1,247,612.69

3 & 4. Total revenue with discounts: ₦1,204,434.17

5. Total discount given away: ₦43,178.52
   - Days 1-5 (15% off all): ₦30,637.79
   - Days 15-20 (10% off A&B): ₦12,540.73


---
## Part B: Pandas Data Analysis (50 points)

### Question 4: Load and Explore Your Dataset (10 points)

**Task:** Find a dataset relevant to your problem domain, or use one of the provided datasets.

**Requirements:**
1. Load the dataset using Pandas
2. Display basic information:
   - Number of rows and columns
   - Column names and data types
   - First 10 rows
   - Statistical summary
   - Check for missing values
3. Write 2-3 sentences describing what this dataset contains

**Deliverable:** Load data into a DataFrame called `df` and provide the exploration

In [5]:
# For this assignment, I'll create a sample Nigerian market dataset
# In practice, you would load from CSV: df = pd.read_csv('your_dataset.csv')

# Creating a sample dataset for demonstration
np.random.seed(123)
n_records = 500

data = {
    'transaction_id': [f'TXN{i:05d}' for i in range(1, n_records + 1)],
    'date': pd.date_range('2024-01-01', periods=n_records, freq='D').tolist(),
    'market': np.random.choice(['Bodija', 'Balogun', 'Ogbete', 'Wuse', 'Ariaria'], n_records),
    'state': np.random.choice(['Oyo', 'Lagos', 'Enugu', 'Abuja', 'Abia'], n_records),
    'product': np.random.choice(['Rice', 'Beans', 'Garri', 'Yam', 'Palm Oil'], n_records),
    'category': np.random.choice(['Grains', 'Oil', 'Tubers'], n_records),
    'quantity': np.random.randint(1, 50, n_records),
    'unit_price': np.random.randint(500, 50000, n_records),
    'vendor': np.random.choice(['Alhaji Musa', 'Mama Ngozi', 'Mr Ade', 'Mrs Okeke'], n_records)
}

df = pd.DataFrame(data)
df['total_amount'] = df['quantity'] * df['unit_price']

# Introduce some missing values for realism
df.loc[np.random.choice(df.index, 20, replace=False), 'quantity'] = np.nan
df.loc[np.random.choice(df.index, 15, replace=False), 'unit_price'] = np.nan

print("Dataset loaded successfully!\n")

# 1. Number of rows and columns
print(f"1. Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns\n")

# 2. Column names and data types
print("2. Column Names and Data Types:")
print(df.dtypes)
print()

# 3. First 10 rows
print("3. First 10 Rows:")
print(df.head(10))
print()

# 4. Statistical summary
print("4. Statistical Summary:")
print(df.describe())
print()

# 5. Check for missing values
print("5. Missing Values:")
print(df.isnull().sum())

Dataset loaded successfully!

1. Dataset Shape: 500 rows, 10 columns

2. Column Names and Data Types:
transaction_id               str
date              datetime64[us]
market                       str
state                        str
product                      str
category                     str
quantity                 float64
unit_price               float64
vendor                       str
total_amount               int64
dtype: object

3. First 10 Rows:
  transaction_id       date   market  state product category  quantity  \
0       TXN00001 2024-01-01   Ogbete   Abia    Rice   Tubers      20.0   
1       TXN00002 2024-01-02  Ariaria  Enugu   Garri   Grains       NaN   
2       TXN00003 2024-01-03   Ogbete  Lagos   Garri   Tubers      24.0   
3       TXN00004 2024-01-04  Balogun  Abuja   Garri      Oil      18.0   
4       TXN00005 2024-01-05     Wuse  Lagos    Rice   Tubers      10.0   
5       TXN00006 2024-01-06   Ogbete  Enugu   Beans   Tubers       NaN   
6       TXN00007 

**Dataset Description:**

This dataset simulates 500 Nigerian market transactions spanning 5 major markets (Bodija, Balogun, Ogbete, Wuse, Ariaria) across 5 states, covering 4 staple food products (Rice, Beans, Garri, Yam, Palm Oil) recorded daily from January 2024. 
Each record captures the vendor, product category, quantity sold, unit price in NGN, and total transaction amount, providing a realistic view of informal market trade patterns in Nigeria. 
The dataset also includes 35 missing values across the `quantity` and `unit_price` columns to simulate real-world data quality issues.

### Question 5: Data Filtering & Selection (10 points)

Using your loaded dataset:

**Tasks:**
1. Select 3 columns of interest and display first 10 rows
2. Filter data based on a numeric condition (e.g., price > some_value)
3. Filter data based on a categorical condition (e.g., state == 'Lagos')
4. Combine two conditions using AND (&) or OR (|)
5. Display the shape of each filtered dataset

**Deliverable:** Show 4 different filtered views of your data


In [6]:
# 1. Select 3 columns of interest and display first 10 rows
selected_cols = df[['product', 'quantity', 'total_amount']].head(10)
print("1. Selected columns (product, quantity, total_amount):")
print(selected_cols)
print(f"   Shape: {selected_cols.shape}\n")

# 2. Filter data based on a numeric condition (total_amount > 100,000)
high_value = df[df['total_amount'] > 100000]
print("2. Transactions with total_amount > ₦100,000:")
print(high_value[['transaction_id', 'product', 'total_amount']].head())
print(f"   Shape: {high_value.shape}\n")

# 3. Filter data based on a categorical condition (state == 'Lagos')
lagos_data = df[df['state'] == 'Lagos']
print("3. Transactions from Lagos:")
print(lagos_data[['transaction_id', 'market', 'product']].head())
print(f"   Shape: {lagos_data.shape}\n")

# 4. Combine two conditions using AND (&) - High value transactions in Lagos
lagos_high_value = df[(df['state'] == 'Lagos') & (df['total_amount'] > 100000)]
print("4. High value transactions (>$100k) in Lagos:")
print(lagos_high_value[['transaction_id', 'market', 'total_amount']].head())
print(f"   Shape: {lagos_high_value.shape}")

1. Selected columns (product, quantity, total_amount):
  product  quantity  total_amount
0    Rice      20.0        217260
1   Garri       NaN         48164
2   Garri      24.0         14592
3   Garri      18.0        243576
4    Rice      10.0         54590
5   Beans       NaN       1285408
6    Rice      12.0        448752
7   Garri       2.0         64716
8   Beans       5.0        237370
9     Yam      32.0        232448
   Shape: (10, 3)

2. Transactions with total_amount > ₦100,000:
  transaction_id product  total_amount
0       TXN00001    Rice        217260
3       TXN00004   Garri        243576
5       TXN00006   Beans       1285408
6       TXN00007    Rice        448752
8       TXN00009   Beans        237370
   Shape: (435, 10)

3. Transactions from Lagos:
   transaction_id   market   product
2        TXN00003   Ogbete     Garri
4        TXN00005     Wuse      Rice
6        TXN00007     Wuse      Rice
8        TXN00009  Balogun     Beans
14       TXN00015  Balogun  Palm Oil
 

### Question 6: Aggregation & Grouping (15 points)

Using your dataset:

**Tasks:**
1. Group by a categorical column and calculate mean of a numeric column
2. Group by a categorical column and calculate multiple statistics (min, max, mean, sum)
3. Create a cross-tabulation or pivot table (if applicable)
4. Find the top 5 records by some criterion
5. Calculate at least one percentage or ratio

**Deliverable:** Perform 5 different aggregations/groupings

In [7]:
print("=== 5 DIFFERENT AGGREGATIONS/GROUPINGS ===\n")

# 1. Group by categorical column and calculate mean of numeric column
print("1. Average quantity sold by product:")
avg_qty_by_product = df.groupby('product')['quantity'].mean().sort_values(ascending=False)
print(avg_qty_by_product)
print()

# 2. Group by categorical column and calculate multiple statistics (min, max, mean, sum)
print("2. Multiple statistics for total_amount by state:")
state_stats = df.groupby('state')['total_amount'].agg(['min', 'max', 'mean', 'sum']).round(2)
print(state_stats)
print()

# 3. Create a cross-tabulation (pivot table)
print("3. Cross-tabulation: Product vs State (total sales count):")
cross_tab = pd.crosstab(df['product'], df['state'], margins=True)
print(cross_tab)
print()

# 4. Find top 5 records by some criterion
print("4. Top 5 highest value transactions:")
top_5 = df.nlargest(5, 'total_amount')[['transaction_id', 'product', 'state', 'total_amount']]
print(top_5)
print()

# 5. Calculate percentage/ratio
print("5. Percentage of total revenue by product:")
revenue_by_product = df.groupby('product')['total_amount'].sum()
revenue_percentage = (revenue_by_product / revenue_by_product.sum() * 100).round(2)
revenue_df = pd.DataFrame({
    'Total Revenue': revenue_by_product,
    'Percentage': revenue_percentage
})
print(revenue_df)

=== 5 DIFFERENT AGGREGATIONS/GROUPINGS ===

1. Average quantity sold by product:
product
Palm Oil    27.176471
Beans       26.130000
Garri       25.902174
Yam         24.410526
Rice        22.252747
Name: quantity, dtype: float64

2. Multiple statistics for total_amount by state:
         min      max       mean       sum
state                                     
Abia    8223  2232932  615219.14  56600161
Abuja  16462  2387664  680200.56  81624067
Enugu   2502  2062134  650738.48  55963509
Lagos   7980  1778781  506537.91  49640715
Oyo     5428  2219904  673133.08  70005840

3. Cross-tabulation: Product vs State (total sales count):
state     Abia  Abuja  Enugu  Lagos  Oyo  All
product                                      
Beans       26     23     22     16   16  103
Garri       18     29     14     20   19  100
Palm Oil    13     26     18     25   21  103
Rice        17     21     16     20   21   95
Yam         18     21     16     17   27   99
All         92    120     86     98 

### Question 7: Data Transformation (15 points)

Using your dataset:

**Tasks:**
1. Create a new column based on a calculation (e.g., total = price × quantity)
2. Create a categorical column based on numeric ranges (e.g., 'Low', 'Medium', 'High')
3. Sort data by 2 or more columns
4. Calculate a rolling or cumulative statistic (if time-series data)
5. Handle any missing values (if present) using appropriate methods

**Deliverable:** Show your transformed dataset with new columns

In [8]:
# Work on a copy of the dataframe
df_transformed = df.copy()

print("=== DATA TRANSFORMATION ===\n")

# 1. Create a new column based on a calculation
print("1. Created 'revenue_per_unit' column (total_amount / quantity):")
df_transformed['revenue_per_unit'] = df_transformed['total_amount'] / df_transformed['quantity']
print(df_transformed[['product', 'quantity', 'total_amount', 'revenue_per_unit']].head())
print()

# 2. Create a categorical column based on numeric ranges
print("2. Created 'price_tier' column (Low, Medium, High, Premium):")
df_transformed['price_tier'] = pd.cut(
    df_transformed['unit_price'],
    bins=[0, 10000, 20000, 40000, float('inf')],
    labels=['Low', 'Medium', 'High', 'Premium']
)
print(df_transformed[['product', 'unit_price', 'price_tier']].head(10))
print()

# 3. Sort data by 2 or more columns
print("3. Sorted by state (ascending) and total_amount (descending):")
df_transformed = df_transformed.sort_values(['state', 'total_amount'], ascending=[True, False])
print(df_transformed[['transaction_id', 'state', 'product', 'total_amount']].head(10))
print()

# 4. Calculate a rolling or cumulative statistic
print("4. Calculated cumulative sum of total_amount by state:")
df_transformed = df_transformed.sort_values('date')  # Sort by date first
df_transformed['cumulative_revenue'] = df_transformed.groupby('state')['total_amount'].cumsum()
print(df_transformed[['date', 'state', 'total_amount', 'cumulative_revenue']].head(10))
print()

# 5. Handle missing values using appropriate methods
print("5. Handling missing values:")
print(f"   Missing before: quantity={df_transformed['quantity'].isnull().sum()}, unit_price={df_transformed['unit_price'].isnull().sum()}")

# Fill missing quantities with median for that product
df_transformed['quantity'] = df_transformed.groupby('product')['quantity'].transform(
    lambda x: x.fillna(x.median())
)

# Fill missing unit_prices with median for that product
df_transformed['unit_price'] = df_transformed.groupby('product')['unit_price'].transform(
    lambda x: x.fillna(x.median())
)

# Recalculate total_amount
df_transformed['total_amount'] = df_transformed['quantity'] * df_transformed['unit_price']

print(f"   Missing after: quantity={df_transformed['quantity'].isnull().sum()}, unit_price={df_transformed['unit_price'].isnull().sum()}")

print("\n=== TRANSFORMED DATASET SAMPLE ===")
print(df_transformed[['transaction_id', 'product', 'price_tier', 'cumulative_revenue']].head())

=== DATA TRANSFORMATION ===

1. Created 'revenue_per_unit' column (total_amount / quantity):
  product  quantity  total_amount  revenue_per_unit
0    Rice      20.0        217260           10863.0
1   Garri       NaN         48164               NaN
2   Garri      24.0         14592             608.0
3   Garri      18.0        243576           13532.0
4    Rice      10.0         54590            5459.0

2. Created 'price_tier' column (Low, Medium, High, Premium):
  product  unit_price price_tier
0    Rice     10863.0     Medium
1   Garri     24082.0       High
2   Garri       608.0        Low
3   Garri     13532.0     Medium
4    Rice      5459.0        Low
5   Beans     40169.0    Premium
6    Rice     37396.0       High
7   Garri     32358.0       High
8   Beans     47474.0    Premium
9     Yam      7264.0        Low

3. Sorted by state (ascending) and total_amount (descending):
    transaction_id state   product  total_amount
423       TXN00424  Abia       Yam       2232932
365      

---
## Part C: Insights & Problem Domain (20 points)

### Question 8: Domain-Specific Analysis (20 points)

**Task:** Answer 3 specific questions about your dataset that are relevant to your problem domain.

**Requirements:**
1. State each question clearly
2. Write code to answer it using NumPy/Pandas
3. Provide interpretation of results (2-3 sentences per question)
4. Create at least one visualization (optional but encouraged)

**Example questions:**
- Healthcare: "What's the distribution of patient ages across clinics?"
- Agriculture: "Which crop has the most price volatility across regions?"
- Education: "What percentage of students score above 70% in each subject?"
- Business: "Which product generates the most revenue per region?"

**Deliverable:** 3 questions + code + interpretations

#### Question 8a: Which product generates the most revenue per region (state)?

In [9]:
print("=== QUESTION 8a: Revenue by Product per State ===\n")

# Calculate total revenue by state and product
revenue_by_state_product = df.groupby(['state', 'product'])['total_amount'].sum().reset_index()

# Find top product in each state
top_product_by_state = revenue_by_state_product.loc[revenue_by_state_product.groupby('state')['total_amount'].idxmax()]

print("Top revenue-generating product in each state:")
for _, row in top_product_by_state.iterrows():
    print(f"  {row['state']}: {row['product']} (₦{row['total_amount']:,.2f})")

# Overall top product
total_by_product = df.groupby('product')['total_amount'].sum().sort_values(ascending=False)
print(f"\nOverall highest revenue product: {total_by_product.index[0]} (₦{total_by_product.iloc[0]:,.2f})")

=== QUESTION 8a: Revenue by Product per State ===

Top revenue-generating product in each state:
  Abia: Beans (₦15,115,929.00)
  Abuja: Palm Oil (₦21,324,870.00)
  Enugu: Rice (₦13,091,376.00)
  Lagos: Palm Oil (₦17,679,416.00)
  Oyo: Yam (₦21,890,354.00)

Overall highest revenue product: Palm Oil (₦74,479,101.00)


**Interpretation:**

The analysis reveals which products are most profitable in each Nigerian state. This information helps vendors and suppliers understand regional preferences and optimize their distribution strategies. For example, if Rice dominates in Lagos but Palm Oil leads in Abuja, suppliers can tailor their inventory accordingly to maximize sales and reduce waste from unsold goods.

#### Question 8b: What is the price volatility (standard deviation) of each product across different markets?

In [10]:
print("=== QUESTION 8b: Price Volatility by Product ===\n")

# Calculate price statistics by product across markets
price_volatility = df.groupby('product')['unit_price'].agg(['mean', 'std', 'min', 'max']).round(2)
price_volatility['coefficient_of_variation'] = (price_volatility['std'] / price_volatility['mean'] * 100).round(2)
price_volatility = price_volatility.sort_values('coefficient_of_variation', ascending=False)

print("Price volatility by product (sorted by coefficient of variation):")
print(price_volatility)

most_volatile = price_volatility.index[0]
least_volatile = price_volatility.index[-1]
print(f"\nMost volatile product: {most_volatile} (CV: {price_volatility.loc[most_volatile, 'coefficient_of_variation']}%)")
print(f"Least volatile product: {least_volatile} (CV: {price_volatility.loc[least_volatile, 'coefficient_of_variation']}%)")

=== QUESTION 8b: Price Volatility by Product ===

Price volatility by product (sorted by coefficient of variation):
              mean       std     min      max  coefficient_of_variation
product                                                                
Beans     23544.11  14342.22   808.0  49793.0                     60.92
Palm Oil  26401.67  15240.79  2402.0  49848.0                     57.73
Rice      25556.79  14453.90   672.0  49925.0                     56.56
Garri     23407.05  13189.67   608.0  49607.0                     56.35
Yam       25677.22  14240.32  1251.0  49824.0                     55.46

Most volatile product: Beans (CV: 60.92%)
Least volatile product: Yam (CV: 55.46%)


**Interpretation:**

Price volatility analysis helps identify which products have unstable prices across markets. 
High volatility products (like seasonal crops) may require price hedging strategies or quick inventory turnover, 
while stable products (like staples) offer predictable margins. 
This insight is crucial for risk management in the Nigerian market, helping traders decide which products to stock based on their risk appetite.

#### Question 8c: Which vendors are the top performers by total sales volume and revenue?

In [11]:
print("=== QUESTION 8c: Top Performing Vendors ===\n")

# Calculate metrics by vendor
vendor_performance = df.groupby('vendor').agg({
    'quantity': ['sum', 'mean'],
    'total_amount': ['sum', 'mean'],
    'transaction_id': 'count'
}).round(2)

# Flatten column names
vendor_performance.columns = ['_'.join(col).strip() for col in vendor_performance.columns]
vendor_performance = vendor_performance.rename(columns={'transaction_id_count': 'total_transactions'})

# Sort by total revenue
vendor_performance = vendor_performance.sort_values('total_amount_sum', ascending=False)

print("Vendor Performance (sorted by total revenue):")
print(vendor_performance)

# Calculate market share
total_revenue = df['total_amount'].sum()
vendor_performance['market_share_pct'] = (vendor_performance['total_amount_sum'] / total_revenue * 100).round(2)

print("\nVendor Market Share:")
for vendor in vendor_performance.index:
    share = vendor_performance.loc[vendor, 'market_share_pct']
    print(f"  {vendor}: {share}%")

=== QUESTION 8c: Top Performing Vendors ===

Vendor Performance (sorted by total revenue):
             quantity_sum  quantity_mean  total_amount_sum  total_amount_mean  \
vendor                                                                          
Mr Ade             3739.0          25.97         100540889          679330.33   
Mama Ngozi         3277.0          27.31          83408160          667265.28   
Mrs Okeke          2462.0          23.67          67007223          614745.17   
Alhaji Musa        2634.0          23.52          62878020          532864.58   

             total_transactions  
vendor                           
Mr Ade                      148  
Mama Ngozi                  125  
Mrs Okeke                   109  
Alhaji Musa                 118  

Vendor Market Share:
  Mr Ade: 32.04%
  Mama Ngozi: 26.58%
  Mrs Okeke: 21.35%
  Alhaji Musa: 20.04%


**Interpretation:**

Vendor performance analysis reveals the key players in the market and their market share. This information is valuable for partnership decisions, competitive analysis, and identifying potential mentors for new vendors. Understanding which vendors generate the most revenue versus those with the highest transaction volume can also reveal different business models - high-volume low-margin versus low-volume high-margin strategies.

---
## Reflection (Required)

1. **What was the most challenging part of this assignment?**
   
   The most challenging part was handling missing values appropriately in Question 7. Deciding whether to drop, fill with mean/median, or use group-specific filling required understanding the data context. Using groupby transform to fill with product-specific medians was the optimal solution.

2. **What NumPy/Pandas concept do you still find confusing?**
   
   Broadcasting in NumPy can be tricky when dealing with arrays of different dimensions. Understanding when and how arrays automatically expand to match shapes requires practice. Also, multi-level groupby operations in Pandas sometimes produce unexpected output formats.

3. **How will you use NumPy/Pandas in your problem domain project?**
   
   NumPy and Pandas will be essential for loading, cleaning, and preprocessing datasets. Pandas' groupby functionality will help analyze patterns across different segments, while NumPy's vectorized operations will speed up feature engineering for machine learning models. The cumulative statistics will be particularly useful for time-series forecasting.

4. **What additional data would help you solve your problem?**
   
   Additional data like customer demographics, seasonal trends, weather data (for agricultural products), competitor pricing, and historical price trends over multiple years would provide deeper insights for forecasting and analysis.